### PR TITLE
MW-11-yes-no-button

### PR DESCRIPTION
**Pull request by Oziel-Sal**
* **Please check if the PR fulfills these requirements**
- [x] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
* It adds a yes and no button to the Match component. It's represented through a React Icon that is a heart and an 'X'. It allows the user to click yes or no for the pet they are interested in.

* **What is the current behavior?What does the code do before you made the new changes?** 
What changed is now we have added a yes or no button. 

* **What is the new behavior?**
The Yes and No button allows user to click either yes or no to like an animal.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
As of now, no changes needed for this PR.

* **Other information**:

### CODE REVIEW

**Review by crissr11 — APPROVED** [review]
Everything looks good and test works. Nice Button design!

**Review by zestybean — CHANGES_REQUESTED** [review]
Everything looks great, but I did run into these warnings after compiling. 

`src/components/AnimalDescription.js
  Line 7:5:    Useless constructor                                                                                                                          no-useless-constructor
  Line 19:54:  Using target="_blank" without rel="noreferrer" is a security risk: see https://html.spec.whatwg.org/multipage/links.html#link-type-noopener  react/jsx-no-target-blank

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.`

I was able to get rid of them by removing the constructor that starts at line 7 and adding `rel="noreferrer"`  to <a> link to the last h2 in the div.

Everything else looks great though!

**Comment by Oziel-Sal** [comment]
@zestybean I hadn't noticed that. I'll go ahead and go fix that thanks.

**Review by zestybean — APPROVED** [review]
Compiler warnings are gone and everything is looking good!

**Pull request merged**
